name: Deploy HTML
on: [push, pull_request]
jobs:
  build:
    name: Deploy HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy index.html
        run: |
          mkdir -p _site
          cp index.html _site/
